---
name: pre-commit-checks
run-name: "${{ github.actor }} has triggered the ${{ github.workflow }} workflow"
on:
  pull_request:
    types:
      - unlabeled
      - labeled
      - synchronize
      - opened
      - reopened
      - edited
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}  # This is the concurrency group name and should be unique per pull request
  cancel-in-progress: ${{ !contains(github.ref, 'release/')}}  # Cancel previous runs if a new run is triggered on a non-release branch
permissions:
  contents: read
  pull-requests: write
jobs:
  pre-commit-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Run Pre-Commit Checks
        id: pre-commit
        uses: nkbinnovations/reusable-actions/.github/actions/pre-commit@v1
        with:
          python_version: '3.13.0'
